// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using roomshare_room_service.Model.Context;

#nullable disable

namespace roomshare_room_service.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20221119040812_AddCEPColumnOnRoom")]
    partial class AddCEPColumnOnRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("roomshare_room_service.Model.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<long>("CEP")
                        .HasColumnType("bigint")
                        .HasColumnName("cep");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("LocatorKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("locator_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("room_key");

                    b.HasKey("Id");

                    b.ToTable("room");
                });
#pragma warning restore 612, 618
        }
    }
}
